In [2]:
# Libraries
import pandas as pd
import pycountry_convert as pc
import numpy as np
import geopy.distance

In [3]:
def get_airports_df():
    airports_df = pd.read_csv("../data/airports.csv", header=None)
    airports_df.columns = ["airport_id", "airport_name", "city", "country", "IATA", "ICAO", "latitude", "longitude", 
                        "altitude", "time_zone", "dst", "tz_database_time_zone", "type", "source"]
    airports_df.drop(["airport_id", "ICAO", "altitude", "time_zone", "dst", "tz_database_time_zone", "type", "source"], axis = 1, inplace = True)
    return airports_df 

airports_df = get_airports_df()
airports_df

,airport_name,city,country,IATA,latitude,longitude
0,Goroka Airport,Goroka,Papua New Guinea,GKA,-6.081690,145.391998
1,Madang Airport,Madang,Papua New Guinea,MAG,-5.207080,145.789001
2,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,-5.826790,144.296005
3,Nadzab Airport,Nadzab,Papua New Guinea,LAE,-6.569803,146.725977
4,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,-9.443380,147.220001
...,...,...,...,...,...,...
7693,Rogachyovo Air Base,Belaya,Russia,\N,71.616699,52.478298
7694,Ulan-Ude East Airport,Ulan Ude,Russia,\N,51.849998,107.737999
7695,Krechevitsy Air Base,Novgorod,Russia,\N,58.625000,31.385000
7696,Desierto de Atacama Airport,Copiapo,Chile,CPO,-27.261200,-70.779198
7697,Melitopol Air Base,Melitopol,Ukraine,\N,46.880001,35.305000

In [4]:
def get_continent_code():
    country_codes = []
    for _, row in airports_df.iterrows():
        try:
            country_code = pc.country_name_to_country_alpha2(row.country, cn_name_format="default")
            continent_code = pc.country_alpha2_to_continent_code(country_code)
            country_codes.append(continent_code)
        except:
            country_codes.append(np.nan)
    return country_codes

airports_df["continent_code"] = get_continent_code()

In [5]:
def drop_null_values():
    for column in airports_df:
        airports_df[column] = airports_df[column].replace([r"\N"],np.nan)
    airports_df.dropna(how="any", inplace=True)

drop_null_values()

In [6]:
airports_df.to_csv('../data/airports_cleaned.csv', index=False)
airports_df

,airport_name,city,country,IATA,latitude,longitude,continent_code
0,Goroka Airport,Goroka,Papua New Guinea,GKA,-6.081690,145.391998,OC
1,Madang Airport,Madang,Papua New Guinea,MAG,-5.207080,145.789001,OC
2,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,-5.826790,144.296005,OC
3,Nadzab Airport,Nadzab,Papua New Guinea,LAE,-6.569803,146.725977,OC
4,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,-9.443380,147.220001,OC
...,...,...,...,...,...,...,...
7684,Bilogai-Sugapa Airport,Sugapa-Papua Island,Indonesia,UGU,-3.739560,137.031998,AS
7687,Ramon Airport,Eilat,Israel,ETM,29.723694,35.011416,AS
7688,Rustaq Airport,Al Masna'ah,Oman,MNH,23.640556,57.487500,AS
7689,Laguindingan Airport,Cagayan de Oro City,Philippines,CGY,8.612203,124.456496,AS
7696,Desierto de Atacama Airport,Copiapo,Chile,CPO,-27.261200,-70.779198,SA

In [7]:
airports_df["IATA"].tolist()

['GKA',
 'MAG',
 'HGU',
 'LAE',
 'POM',
 'WWK',
 'UAK',
 'GOH',
 'SFJ',
 'THU',
 'AEY',
 'EGS',
 'HFN',
 'HZK',
 'IFJ',
 'KEF',
 'PFJ',
 'RKV',
 'SIJ',
 'VEY',
 'YAM',
 'YAY',
 'YAZ',
 'YBB',
 'YBC',
 'YBG',
 'YBK',
 'YBL',
 'YBR',
 'YCB',
 'YCD',
 'YCG',
 'YCH',
 'YCL',
 'YCO',
 'YCT',
 'YCW',
 'YCY',
 'YZS',
 'YDA',
 'YDB',
 'YDF',
 'YDL',
 'YDN',
 'YDQ',
 'YEG',
 'YEK',
 'YEN',
 'YET',
 'YEU',
 'YEV',
 'YFB',
 'YFC',
 'YFE',
 'YFO',
 'YFR',
 'YFS',
 'YGK',
 'YGL',
 'YGP',
 'YGQ',
 'YGR',
 'YHB',
 'YHD',
 'YHI',
 'YHK',
 'YHM',
 'YHU',
 'YHY',
 'YHZ',
 'YIB',
 'YIO',
 'YJN',
 'YJT',
 'YKA',
 'YKF',
 'YKL',
 'YKY',
 'YKZ',
 'YLD',
 'YLJ',
 'YLL',
 'YLT',
 'YLW',
 'YMA',
 'YMJ',
 'YMM',
 'YMO',
 'YMW',
 'YMX',
 'YNA',
 'YND',
 'YNM',
 'YOC',
 'YOD',
 'YOJ',
 'YOW',
 'YPA',
 'YPE',
 'YPG',
 'YPL',
 'YPN',
 'YPQ',
 'YPR',
 'YPY',
 'YQA',
 'YQB',
 'YQF',
 'YQG',
 'YQH',
 'YQK',
 'YQL',
 'YQM',
 'YQQ',
 'YQR',
 'YQT',
 'YQU',
 'YQV',
 'YQW',
 'YQX',
 'YQY',
 'YQZ',
 'YRB',
 'YRI',
 'YRJ',
 'YRM',
 'YRT',
 'YSB',
 'YSC',
 'YSJ',
 'YSM',
 'YSR',
 'YSU',
 'YSY',
 'YTE',
 'YTH',
 'YTR',
 'YTS',
 'YTZ',
 'YUB',
 'YUL',
 'YUT',
 'YUX',
 'YUY',
 'YVC',
 'YVG',
 'YVM',
 'YVO',
 'YVP',
 'YVQ',
 'YVR',
 'YVT',
 'YVV',
 'YWA',
 'YWG',
 'YWK',
 'YWL',
 'YWY',
 'YXC',
 'YXD',
 'YXE',
 'YXH',
 'YXJ',
 'YXL',
 'YXP',
 'YXR',
 'YXS',
 'YXT',
 'YXU',
 'YXX',
 'YXY',
 'YYB',
 'YYC',
 'YYD',
 'YYE',
 'YYF',
 'YYG',
 'YYH',
 'YYJ',
 'YYL',
 'YYN',
 'YYQ',
 'YYR',
 'YYT',
 'YYU',
 'YYW',
 'YYY',
 'YYZ',
 'YZD',
 'YZE',
 'YZF',
 'YZH',
 'YZP',
 'YZR',
 'YZT',
 'YZU',
 'YZV',
 'YZW',
 'YZX',
 'ZFA',
 'ZFM',
 'QLD',
 'BUJ',
 'BJA',
 'ALG',
 'DJG',
 'VVZ',
 'TMR',
 'GJL',
 'MZW',
 'AAE',
 'CZL',
 'TEE',
 'HRM',
 'TID',
 'TIN',
 'CFK',
 'TAF',
 'TLM',
 'ORN',
 'BFW',
 'MUW',
 'AZR',
 'BSK',
 'ELG',
 'GHA',
 'HME',
 'INZ',
 'TGR',
 'LOO',
 'TMX',
 'OGX',
 'IAM',
 'COO',
 'OUA',
 'BOY',
 'ACC',
 'TML',
 'NYI',
 'TKD',
 'ABV',
 'AKR',
 'BNI',
 'CBQ',
 'ENU',
 'IBA',
 'ILR',
 'JOS',
 'KAD',
 'KAN',
 'MIU',
 'MDI',
 'LOS',
 'MXJ',
 'PHC',
 'SKO',
 'YOL',
 'ZAR',
 'MFQ',
 'NIM',
 'THZ',
 'AJY',
 'ZND',
 'MIR',
 'TUN',
 'GAF',
 'GAE',
 'DJE',
 'EBM',
 'SFA',
 'TOE',
 'LRL',
 'LFW',
 'ANR',
 'BRU',
 'CRL',
 'KJK',
 'LGG',
 'OST',
 'OBL',
 'AOC',
 'IES',
 'REB',
 'QXH',
 'BBH',
 'ZMG',
 'CBU',
 'SXF',
 'DRS',
 'ERF',
 'FRA',
 'FMO',
 'HAM',
 'THF',
 'CGN',
 'DUS',
 'MUC',
 'NUE',
 'LEJ',
 'SCN',
 'STR',
 'TXL',
 'HAJ',
 'BRE',
 'QEF',
 'HHN',
 'MHG',
 'EIB',
 'SGE',
 'XFW',
 'KEL',
 'LBC',
 'ESS',
 'BFE',
 'MGL',
 'PAD',
 'DTM',
 'AGB',
 'OBF',
 'RBM',
 'FDH',
 'SZW',
 'BYU',
 'URD',
 'HOQ',
 'ZQW',
 'ZQL',
 'BWE',
 'KSF',
 'BRV',
 'EME',
 'WVN',
 'BMK',
 'NRD',
 'FLF',
 'GWT',
 'KDL',
 'URE',
 'EPU',
 'TLL',
 'TAY',
 'ENF',
 'KEV',
 'HEM',
 'HEL',
 'HYV',
 'KTQ',
 'IVL',
 'JOE',
 'JYV',
 'KAU',
 'KEM',
 'KAJ',
 'KHJ',
 'KOK',
 'KAO',
 'KTT',
 'KUO',
 'QLF',
 'LPP',
 'MHQ',
 'MIK',
 'OUL',
 'POR',
 'RVN',
 'SVL',
 'SOT',
 'TMP',
 'TKU',
 'UTI',
 'VAA',
 'VRK',
 'YLI',
 'BFS',
 'ENK',
 'BHD',
 'LDY',
 'BHX',
 'CVT',
 'GLO',
 'GBA',
 'MAN',
 'NQY',
 'LYE',
 'YEO',
 'HAW',
 'CWL',
 'SWS',
 'BRS',
 'LPL',
 'LTN',
 'PLH',
 'BOH',
 'SOU',
 'QLA',
 'ACI',
 'GCI',
 'JER',
 'ESH',
 'BQH',
 'LGW',
 'LCY',
 'FAB',
 'BBS',
 'LHR',
 'SEN',
 'LYX',
 'MSE',
 'CAX',
 'BLK',
 'HUY',
 'BWF',
 'LBA',
 'WRT',
 'CEG',
 'IOM',
 'NCL',
 'MME',
 'EMA',
 'KOI',
 'LSI',
 'WIC',
 'ABZ',
 'INV',
 'GLA',
 'EDI',
 'ILY',
 'PIK',
 'BEB',
 'SCS',
 'DND',
 'SYY',
 'TRE',
 'ADX',
 'LMO',
 'CBG',
 'NWI',
 'STN',
 'EXT',
 'FZO',
 'OXF',
 'BEX',
 'LKZ',
 'MHZ',
 'QUY',
 'FFD',
 'BZZ',
 'ODH',
 'NHT',
 'QCY',
 'BEQ',
 'SQZ',
 'HRT',
 'WTN',
 'KNF',
 'MPN',
 'AMS',
 'MST',
 'EIN',
 'GRQ',
 'GLZ',
 'DHR',
 'LEY',
 'LWR',
 'RTM',
 'UTC',
 'ENS',
 'LID',
 'WOE',
 'ORK',
 'GWY',
 'DUB',
 'NOC',
 'KIR',
 'SNN',
 'SXL',
 'WAT',
 'AAR',
 'BLL',
 'CPH',
 'EBJ',
 'KRP',
 'BYR',
 'MRW',
 'ODE',
 'RKE',
 'RNN',
 'SGD',
 'SKS',
 'SQW',
 'TED',
 'FAE',
 'STA',
 'AAL',
 'LUX',
 'AES',
 'ANX',
 'ALF',
 'BNN',
 'BOO',
 'BGO',
 'BJF',
 'KRS',
 'DLD',
 'BDU',
 'EVE',
 'VDB',
 'FRO',
 'OSL',
 'HAU',
 'HAA',
 'KSU',
 'KKN',
 'FAN',
 'MOL',
 'MJF',
 'LKL',
 'NTB',
 'OLA',
 'RRS',
 'RYG',
 'LYR',
 'SKE',
 'SRP',
 'SSJ',
 'TOS',
 'TRF',
 'TRD',
 'SVG',
 'GDN',
 'KRK',
 'KTW',
 'POZ',
 'RZE',
 'SZZ',
 'OSP',
 'WAW',
 'WRO',
 'IEG',
 'RNB',
 'GOT',
 'JKG',
 'LDK',
 'GSE',
 'KVB',
 'THN',
 'KSK',
 'MXX',
 'NYO',
 'KID',
 'OSK',
 'KLR',
 'MMX',
 'HAD',
 'VXO',
 'EVG',
 'GEV',
 'HUV',
 'KRF',
 'LYC',
 'SDL',
 'OER',
 'KRN',
 'SFT',
 'UME',
 'VHM',
 'AJR',
 'ORB',
 'VST',
 'LLA',
 'ARN',
 'BMA',
 'BLE',
 'HLF',
 'GVX',
 'LPI',
 'NRK',
 'EKT',
 'VBY',
 'SPM',
 'RMS',
 'GHF',
 'ZCN',
 'FRZ',
 'ZNF',
 'KZG',
 'FCN',
 'GKE',
 'RLG',
 'WBG',
 'WIE',
 'FEL',
 'IGS',
 'GUT',
 'ALJ',
 'AGZ',
 'BIY',
 'BFN',
 'CPT',
 'DUR',
 'ELS',
 'FCB',
 'GCJ',
 'GRJ',
 'HRS',
 'HDS',
 'JNB',
 'KXE',
 'KIM',
 'KMH',
 'KLZ',
 'HLA',
 'SDB',
 'LAY',
 'MGH',
 'LLE',
 'MZQ',
 'NCS',
 'OVG',
 'OUH',
 'PLZ',
 'PBZ',
 'PHW',
 'JOH',
 'PZB',
 'NTY',
 'PTG',
 'PCF',
 'UTW',
 'RCB',
 'ROD',
 'SBU',
 'ZEC',
 'SIS',
 'SZK',
 'LTA',
 'ULD',
 'UTN',
 'UTT',
 'VRU',
 'VIR',
 'VRE',
 'PRY',
 'WKF',
 'FRW',
 'JWA',
 'BBK',
 'MUB',
 'GBE',
 'PKW',
 'MTS',
 'BGF',
 'BBT',
 'BSG',
 'SSG',
 'MRU',
 'RRG',
 'NKW',
 'TKC',
 'DLA',
 'MVR',
 'FOM',
 'NGE',
 'GOU',
 'BFX',
 'BPC',
 'YAO',
 'CGJ',
 'LVI',
 'LUN',
 'MFU',
 'MNR',
 'NLA',
 'KIW',
 'HAH',
 'NWA',
 'AJN',
 'DZA',
 'TNR',
 'ZVA',
 'SMS',
 'TMM',
 'MOQ',
 'DIE',
 'WMR',
 'ZWA',
 'AMB',
 'ANM',
 'HVA',
 'MJN',
 'NOS',
 'BPY',
 'WMN',
 'SVB',
 'VOH',
 'WAI',
 'IVA',
 'FTU',
 'WFI',
 'RVA',
 'WVK',
 'MNJ',
 'MXM',
 'TLE',
 'SSY',
 'BUG',
 'CAB',
 'NOV',
 'SVP',
 'LAD',
 'MEG',
 'SPP',
 'GXG',
 'PBN',
 'VHC',
 'SZA',
 'SDD',
 'LUO',
 'UGO',
 'XGN',
 'OYE',
 'OKN',
 'LBQ',
 'BMM',
 'POG',
 'OMB',
 'MKU',
 'LBV',
 'MVB',
 'PCP',
 'TMS',
 'BEW',
 'INH',
 'VXC',
 'LFB',
 'MPM',
 'MUD',
 'MZB',
 'MNC',
 'APL',
 'POL',
 'UEL',
 'TET',
 'VNX',
 'DES',
 'SEZ',
 'PRI',
 'AEH',
 'MQQ',
 'NDJ',
 'FYT',
 'BUQ',
 'BFO',
 'VFA',
 'HRE',
 'KAB',
 'UTA',
 'MVZ',
 'GWE',
 'HWN',
 'BLZ',
 'KGJ',
 'KBQ',
 'LLW',
 'ZZU',
 'MSU',
 'BKO',
 'GAQ',
 'KYS',
 'MZI',
 'TOM',
 'BJL',
 'FUE',
 'VDE',
 'SPC',
 'LPA',
 'ACE',
 'TFS',
 'TFN',
 'MLN',
 'FNA',
 'MLW',
 'ROB',
 'AGA',
 'TTA',
 'FEZ',
 'ERH',
 'MEK',
 'OUD',
 'GMD',
 'RBA',
 'CMN',
 'RAK',
 'NNA',
 'OZZ',
 'AHU',
 'TTU',
 'TNG',
 'ZIG',
 'CSK',
 'KLC',
 'DKR',
 'XLS',
 'BXE',
 'KGG',
 'TUD',
 'AEO',
 'TIY',
 'KFA',
 'EMN',
 'KED',
 'NKC',
 'SEY',
 'ATR',
 'NDB',
 'FIG',
 'FAA',
 'LEK',
 'SID',
 'BVC',
 'MMO',
 'SNE',
 'VXE',
 'ADD',
 'AMH',
 'AXU',
 'BJR',
 'DIR',
 'GMB',
 'GDQ',
 'JIM',
 'LLI',
 'MQX',
 'ASO',
 'BJM',
 'HGA',
 'BBO',
 'KMU',
 'ALY',
 'ABS',
 'CAI',
 'CWE',
 'HRG',
 'EGH',
 'LXR',
 'MUH',
 'PSD',
 'SKV',
 'ASW',
 'ELT',
 'EDL',
 'GGM',
 'KIS',
 'KTL',
 'LOK',
 'LAU',
 'MBA',
 'WIL',
 'WJR',
 'GHT',
 'AKF',
 'BEN',
 'SEB',
 'TIP',
 'LMQ',
 'HUQ',
 'LTD',
 'GYI',
 'KGL',
 'KME',
 'DOG',
 'RSS',
 'ELF',
 'KSL',
 'KDX',
 'EBD',
 'JUB',
 'MAK',
 'KRT',
 'ARK',
 'DAR',
 'DOD',
 'IRI',
 'JRO',
 'LKY',
 'MYW',
 'MWZ',
 'PMA',
 'TGT',
 'ZNZ',
 'EBB',
 'SRT',
 'TIA',
 'BOJ',
 'GOZ',
 'PDV',
 'SOF',
 'SZR',
 'VAR',
 'LCA',
 'PFO',
 'AKT',
 'DBV',
 'OSI',
 'PUY',
 'RJK',
 'SPU',
 'ZAG',
 'ZAD',
 'ABC',
 'ALC',
 'LEI',
 'OVD',
 'ODB',
 'BIO',
 'BCN',
 'BJZ',
 'LCG',
 'GRO',
 'GRX',
 'IBZ',
 'XRY',
 'MJV',
 'MAD',
 'AGP',
 'MAH',
 'OZP',
 'PNA',
 'REU',
 'ROZ',
 'SLM',
 'EAS',
 'SCQ',
 'LEU',
 'TOJ',
 'VLC',
 'VLL',
 'VIT',
 'VGO',
 'SDR',
 'ZAZ',
 'SVQ',
 'CQF',
 'BYF',
 'LTQ',
 'XVS',
 'AGF',
 'BOD',
 'EGC',
 'CNG',
 'PIS',
 'MCU',
 'LIG',
 'NIT',
 'TLS',
 'PUF',
 'LDE',
 'ANG',
 'BVE',
 'PGX',
 'BIQ',
 'ZAO',
 'LBI',
 'DCM',
 'RDZ',
 'RYN',
 'XMW',
 'RCO',
 'CMR',
 'DLE',
 'OBS',
 'LPY',
 'ETZ',
 'BIA',
 'CLY',
 'FSC',
 'AJA',
 'PRP',
 'SOZ',
 'AUF',
 'CMF',
 'CFE',
 'BOU',
 'QNJ',
 'LYS',
 'SYT',
 'RNE',
 'NCY',
 'GNB',
 'VAF',
 'VHY',
 'AUR',
 'CHR',
 'LYN',
 'CEQ',
 'EBU',
 'CCF',
 'MRS',
 'NCE',
 'XOG',
 ...]

In [6]:
def get_routes_df():
    routes = pd.read_csv("../data/routes.csv", header=None)
    routes.columns = ["airline", "airline_id", "source", "source_airport_id", "destination", 
                        "destination_airport_id", "codeshare", "stops", "equipment"]
    routes.drop(["airline", "airline_id", "source_airport_id", "destination_airport_id", "codeshare", "stops", "equipment"], axis = 1, inplace = True)
    routes.drop_duplicates(subset=["source", "destination"], inplace=True)
    return routes

routes = get_routes_df()
routes

      source destination
0        AER         KZN
1        ASF         KZN
2        ASF         MRV
3        CEK         KZN
4        CEK         OVB
...      ...         ...
67653    TSV         WIN
67654    WGA         MEL
67656    WIN         LRE
67657    WIN         TSV
67658    WYA         ADL

[37595 rows x 2 columns]

In [7]:
def merge_dataframes():
    routes_source = pd.merge(left=routes, right=airports_df[["IATA","latitude","longitude","continent_code"]], left_on="source", right_on="IATA")
    routes_source.drop(["IATA"], axis = 1, inplace = True)
    routes_source.rename(columns={"latitude":"source_lat", "longitude":"source_lon", "continent_code":"source_code"}, inplace=True)

    routes_df = pd.merge(left=routes_source, right=airports_df[["IATA","latitude","longitude","continent_code"]], left_on="destination", right_on="IATA")
    routes_df.drop(["IATA"], axis = 1, inplace = True)
    routes_df.rename(columns={"latitude":"dest_lat", "longitude":"dest_lon", "continent_code":"dest_code"}, inplace=True)
    
    return routes_df

routes_df = merge_dataframes()
routes_df

,source,destination,source_lat,source_lon,source_code,dest_lat,dest_lon,dest_code
0,AER,KZN,43.449902,39.956600,EU,55.606201,49.278702,EU
1,ASF,KZN,46.283298,48.006302,EU,55.606201,49.278702,EU
2,CEK,KZN,55.305801,61.503300,EU,55.606201,49.278702,EU
3,DME,KZN,55.408798,37.906300,EU,55.606201,49.278702,EU
4,EGO,KZN,50.643799,36.590099,EU,55.606201,49.278702,EU
...,...,...,...,...,...,...,...,...
36601,ZKE,YFA,52.282501,-81.677803,NA,52.201401,-81.696899,NA
36602,YPO,YAT,54.988098,-85.443298,NA,52.927502,-82.431900,NA
36603,ZKE,YAT,52.282501,-81.677803,NA,52.927502,-82.431900,NA
36604,JCK,RCM,-20.668301,141.723007,OC,-20.701900,143.115005,OC
36605,TRO,GFN,-31.888599,152.514008,OC,-29.759399,153.029999,OC

In [8]:
def get_distance():  
    distance = []
    for i in range(len(routes_df)):
        source = (routes_df.source_lat[i], routes_df.source_lon[i])
        dest = (routes_df.dest_lat[i], routes_df.dest_lon[i])
        distance.append(geopy.distance.distance(source, dest).km)
    return np.round(distance, 2)

routes_df["distance"] = get_distance()

In [9]:
routes_df.to_csv('../data/routes_cleaned.csv', index=False)
routes_df

,source,destination,source_lat,source_lon,source_code,dest_lat,dest_lon,dest_code,distance
0,AER,KZN,43.449902,39.956600,EU,55.606201,49.278702,EU,1507.99
1,ASF,KZN,46.283298,48.006302,EU,55.606201,49.278702,EU,1040.94
2,CEK,KZN,55.305801,61.503300,EU,55.606201,49.278702,EU,773.13
3,DME,KZN,55.408798,37.906300,EU,55.606201,49.278702,EU,718.08
4,EGO,KZN,50.643799,36.590099,EU,55.606201,49.278702,EU,1010.82
...,...,...,...,...,...,...,...,...,...
36601,ZKE,YFA,52.282501,-81.677803,NA,52.201401,-81.696899,NA,9.12
36602,YPO,YAT,54.988098,-85.443298,NA,52.927502,-82.431900,NA,302.73
36603,ZKE,YAT,52.282501,-81.677803,NA,52.927502,-82.431900,NA,88.10
36604,JCK,RCM,-20.668301,141.723007,OC,-20.701900,143.115005,OC,145.08
36605,TRO,GFN,-31.888599,152.514008,OC,-29.759399,153.029999,OC,241.16